### ISSUE TITLE
Kennlernspiel vorbereiten

### ISSUE THREAD

**Issue by sophiemie** [sophiemie/ExperimentAufwindkraftwerk#21]
## Akzeptanzkriterien
- [x] Kategorien Brainstorming von Vorstellung der Role Models
- [x] Kategorien von @sophiemie zusammenfassen
- [x] Kategorien von @svantje zusammenfassen
- [x] Kategorien von @totallynotjose zusammenfassen
- [x] Kategorien von @ValeriaSchwab zusammenfassen
- [x] Auf Kategorien einigen
- [x] Karten vorbereiten (Farben drucken)
- [x] Beschreibung für Susanne

## Schülerinnen Kennenlernen
- [x] Spiel Brainstorming
- [x] Fragen sammeln
- [x] Fragen auwählen
- [x] Spiel vorbereiten für Veranstaltung

## DoD
- [x] Fertiges Kennlernspiel

**Comment by totallynotjose** [comment]
Kategorien: Hobbys, Studiengang, Alter, Gegenstand, Haustiere, Farbe, bester Urlaub bisher, Leistungskurs (Schule)
(Studiengang als letztes, ggf. Gegenstand als vorletztes)

**Comment by totallynotjose** [comment]
Hobbys: Lesen, Sport, Häkeln
Studiengang: Bionik
Alter: 21
Gegenstand: 
Haustiere: 3 Katzen
Farbe: phthalogrün
bester Urlaub: Kiel
Leistungskurse: Mathe und Physik
Davon habe ich ganz viel: bunte Socken
Ich habe in meinem Studium schon mal: das Brechverhalten von Karotten und Rettich untersucht

**Comment by svantje** [comment]
Hobbys: Singen im Chor, kreatives Schreiben, Fotografieren
Sport: Fahrrad fahren, Volleyball 
Studiengang: Luft- und Raumfahrttechnik
Alter: 21
Gegenstand: Alu Flufzeug Modell
Haustiere: Hund (Fussel), ein Pony und ein Pferd
Farbe: Piniengrün so wie mein Handy und so
bester Urlaub: Outdoor Urlaub auf den Lofoten
Leistungskursen: Physik und Mathe
Davon habe ich ganz viel: Notizbücher und schöne Stifte
Ich habe in meinem Studium schonmal: 4 Wochen in der Werkstatt gestanden und mit Holz gearbeitet 
Das wollte ich werden als ich klein war: Naturforscherin

**Comment by svantje** [comment]
Kennenlernen mit allen: 

- Was würdest du eher
- Fragen im Glas/ Speeddating

**Comment by totallynotjose** [comment]
Kategorien für was würdest du eher:
Zum Mond fliegen oder Computer hacken?
Mit dem Kopf oder mit den Händen arbeiten?
Lieber die Tiefsee oder den Weltraum erforschen?
Arbeitest du lieber im Team oder alleine?
Lieber in einem kleinen Bereich gut auskennen oder in ganz vielen Bereichen etwas auskennen?

**Comment by totallynotjose** [comment]
vielleicht was würdest du eher zuerst machen, dann die raten lassen

**Comment by ValeriaSchwab** [comment]
Hobbys: Lesen, (Formula Student Team Bremen - Bremergy)
Studiengang: Maschinenbau
Alter: 21
Gegenstand: Ferrari-F1-Rennwagen
Haustiere: leider nein :/
Farbe: babyblau, pastell lila
Bester Urlaub: Barcelona-Catalunya, Nürburg
Leistungskurs/Schwerpunkt in Schule: Mathe, Physik, Französisch
Davon habe ich ganz viel: Theaterkarten
Ich habe habe in meinem Studium schonmal... : eine Vorrichtung konstruiert, (mit Lego-Flugzeugmodellen gearbeitet)
Sport: Fitness
Das wollte ich werden als ich klein war: Lehrerin

**Comment by sophiemie** [comment]
Finale Kategorien 
1. Alter (als Beispiel)
2. Hobbys
3. Farbe
4. Davon habe ich ganz viel....
5. Leistungskurs
6. Das habe ich schonmal gemacht...
7. Gegenstand
8. Studiengang

**Comment by svantje** [comment]
https://www.moderatorenshop.de/equipment/time-timer-icebreaker/timetimer/time-timer-mod

der coole Timer für 66,52€
